"""empty message

Revision ID: 35fc7d1786a1
Revises: a8267f67b9cb
Create Date: 2022-11-08 19:13:10.153684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "35fc7d1786a1"
down_revision = "a8267f67b9cb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tweet",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=True),
        sa.Column("text", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tweet")
    # ### end Alembic commands ###
